## Import Library & Configuration

In [ ]:
import pandas as pd
import numpy as np
from pathlib import Path

# Reproducibility
np.random.seed(42)

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

## Buat Folder Dataset

In [ ]:
# Project directories
BASE_DIR = Path(".")

RAW_DIR = BASE_DIR / "data" / "raw"
PROCESSED_DIR = BASE_DIR / "data" / "processed"

RAW_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("Raw data directory :", RAW_DIR)
print("Processed directory :", PROCESSED_DIR)

Raw data directory : data/raw
Processed directory : data/processed

## Periode Data

In [ ]:
dates = pd.date_range(
    start="2019-01-01",
    end="2025-12-01",
    freq="MS"
)

print("Start:", dates.min())
print("End  :", dates.max())
print("Number of months:", len(dates))

# 7 tahun × 12 bulan = 84 bulan

Start: 2019-01-01 00:00:00
End  : 2025-12-01 00:00:00
Number of months: 84

## Master Estate

In [ ]:
estate_data = {
    "estate_id": [
        "EST001", "EST002", "EST003", "EST004", "EST005",
        "EST006", "EST007", "EST008", "EST009", "EST010"
    ],

    "estate_name": [
        "Estate Lampung 01",
        "Estate Lampung 02",
        "Estate Sumsel 01",
        "Estate Jambi 01",
        "Estate Riau 01",
        "Estate Kalbar 01",
        "Estate Kalteng 01",
        "Estate Kaltim 01",
        "Estate Sulawesi 01",
        "Estate Sulawesi 02"
    ],

    "region": [
        "Sumatra",
        "Sumatra",
        "Sumatra",
        "Sumatra",
        "Sumatra",
        "Kalimantan",
        "Kalimantan",
        "Kalimantan",
        "Sulawesi",
        "Sulawesi"
    ],

    "area_ha": [
        4250,
        3800,
        5100,
        4600,
        5500,
        4100,
        4700,
        3900,
        3600,
        4300
    ],

    "planting_year": [
        2010,
        2012,
        2009,
        2011,
        2008,
        2013,
        2010,
        2014,
        2011,
        2012
    ]
}

df_estate = pd.DataFrame(estate_data)

df_estate

  estate_id         estate_name      region  area_ha  planting_year
0    EST001   Estate Lampung 01     Sumatra     4250           2010
1    EST002   Estate Lampung 02     Sumatra     3800           2012
2    EST003    Estate Sumsel 01     Sumatra     5100           2009
3    EST004     Estate Jambi 01     Sumatra     4600           2011
4    EST005      Estate Riau 01     Sumatra     5500           2008
5    EST006    Estate Kalbar 01  Kalimantan     4100           2013
6    EST007   Estate Kalteng 01  Kalimantan     4700           2010
7    EST008    Estate Kaltim 01  Kalimantan     3900           2014
8    EST009  Estate Sulawesi 01    Sulawesi     3600           2011
9    EST010  Estate Sulawesi 02    Sulawesi     4300           2012

## Karakteristik Produksi Estate

In [ ]:
production_capacity = {
    "EST001": 2.05,
    "EST002": 2.10,
    "EST003": 2.00,
    "EST004": 2.15,
    "EST005": 2.05,
    "EST006": 2.20,
    "EST007": 2.10,
    "EST008": 2.25,
    "EST009": 2.00,
    "EST010": 2.10
}

rainfall_base = {
    "Sumatra": 220,
    "Kalimantan": 250,
    "Sulawesi": 190
}

df_estate["base_yield_ton_ha"] = df_estate["estate_id"].map(
    production_capacity
)

df_estate["base_rainfall_mm"] = df_estate["region"].map(
    rainfall_base
)

df_estate

,estate_id,estate_name,region,area_ha,planting_year,base_yield_ton_ha,base_rainfall_mm
0,EST001,Estate Lampung 01,Sumatra,4250,2010,2.05,220
1,EST002,Estate Lampung 02,Sumatra,3800,2012,2.10,220
2,EST003,Estate Sumsel 01,Sumatra,5100,2009,2.00,220
3,EST004,Estate Jambi 01,Sumatra,4600,2011,2.15,220
4,EST005,Estate Riau 01,Sumatra,5500,2008,2.05,220
5,EST006,Estate Kalbar 01,Kalimantan,4100,2013,2.20,250
6,EST007,Estate Kalteng 01,Kalimantan,4700,2010,2.10,250
7,EST008,Estate Kaltim 01,Kalimantan,3900,2014,2.25,250
8,EST009,Estate Sulawesi 01,Sulawesi,3600,2011,2.00,190
9,EST010,Estate Sulawesi 02,Sulawesi,4300,2012,2.10,190

## Generate Kombinasi Estate × Month

In [ ]:
# setiap estate mempunyai observasi untuk setiap bulan.
df_base = pd.MultiIndex.from_product(
    [
        df_estate["estate_id"],
        dates
    ],
    names=["estate_id", "date"]
).to_frame(index=False)

df_base.head()

  estate_id       date
0    EST001 2019-01-01
1    EST001 2019-02-01
2    EST001 2019-03-01
3    EST001 2019-04-01
4    EST001 2019-05-01

In [ ]:
print("Expected rows:", len(df_estate) * len(dates))
print("Actual rows  :", len(df_base))

Expected rows: 840
Actual rows  : 840

## Gabung Informasi Estate

In [ ]:
df_base = df_base.merge(
    df_estate,
    on="estate_id",
    how="left"
)

df_base.head()

,estate_id,date,estate_name,region,area_ha,planting_year,base_yield_ton_ha,base_rainfall_mm
0,EST001,2019-01-01,Estate Lampung 01,Sumatra,4250,2010,2.05,220
1,EST001,2019-02-01,Estate Lampung 01,Sumatra,4250,2010,2.05,220
2,EST001,2019-03-01,Estate Lampung 01,Sumatra,4250,2010,2.05,220
3,EST001,2019-04-01,Estate Lampung 01,Sumatra,4250,2010,2.05,220
4,EST001,2019-05-01,Estate Lampung 01,Sumatra,4250,2010,2.05,220

## hitung Plant Age

In [ ]:
df_base["plant_age_years"] = (
    df_base["date"].dt.year
    - df_base["planting_year"]
)

df_base[
    ["estate_id", "date", "planting_year", "plant_age_years"]
].head(10)

  estate_id       date  planting_year  plant_age_years
0    EST001 2019-01-01           2010                9
1    EST001 2019-02-01           2010                9
2    EST001 2019-03-01           2010                9
3    EST001 2019-04-01           2010                9
4    EST001 2019-05-01           2010                9
5    EST001 2019-06-01           2010                9
6    EST001 2019-07-01           2010                9
7    EST001 2019-08-01           2010                9
8    EST001 2019-09-01           2010                9
9    EST001 2019-10-01           2010                9

## buat Seasonality

In [ ]:
# Karena produksi perkebunan bisa memiliki pola musiman, kita buat seasonal factor berdasarkan bulan.
# Jadi nanti kita akan mempunyai pola:
seasonal_factor = {
    1: 0.95,
    2: 0.97,
    3: 1.02,
    4: 1.05,
    5: 1.08,
    6: 1.12,
    7: 1.15,
    8: 1.12,
    9: 1.05,
    10: 1.00,
    11: 0.96,
    12: 0.93
}

df_base["month"] = df_base["date"].dt.month

df_base["seasonal_factor"] = df_base["month"].map(
    seasonal_factor
)

df_base[
    ["date", "month", "seasonal_factor"]
].drop_duplicates().sort_values("date")

         date  month  seasonal_factor
0  2019-01-01      1             0.95
1  2019-02-01      2             0.97
2  2019-03-01      3             1.02
3  2019-04-01      4             1.05
4  2019-05-01      5             1.08
..        ...    ...              ...
79 2025-08-01      8             1.12
80 2025-09-01      9             1.05
81 2025-10-01     10             1.00
82 2025-11-01     11             0.96
83 2025-12-01     12             0.93

[84 rows x 3 columns]

## Generate Rainfall

In [ ]:
# Kita menggunakan: regional rainfall baseline, seasonality, random variation
rainfall_seasonal = {
    1: 1.15,
    2: 1.10,
    3: 1.05,
    4: 0.95,
    5: 0.90,
    6: 0.85,
    7: 0.80,
    8: 0.82,
    9: 0.90,
    10: 1.00,
    11: 1.10,
    12: 1.18
}

df_base["rainfall_factor"] = df_base["month"].map(
    rainfall_seasonal
)

rainfall_noise = np.random.normal(
    loc=0,
    scale=25,
    size=len(df_base)
)

df_base["rainfall_mm"] = (
    df_base["base_rainfall_mm"]
    * df_base["rainfall_factor"]
    + rainfall_noise
)

df_base["rainfall_mm"] = (
    df_base["rainfall_mm"]
    .clip(lower=80)
    .round(1)
)

In [ ]:
df_base[
    ["estate_id", "date", "region", "rainfall_mm"]
].head(15)

   estate_id       date   region  rainfall_mm
0     EST001 2019-01-01  Sumatra       265.40
1     EST001 2019-02-01  Sumatra       238.50
2     EST001 2019-03-01  Sumatra       247.20
3     EST001 2019-04-01  Sumatra       247.10
4     EST001 2019-05-01  Sumatra       192.10
5     EST001 2019-06-01  Sumatra       181.10
6     EST001 2019-07-01  Sumatra       215.50
7     EST001 2019-08-01  Sumatra       199.60
8     EST001 2019-09-01  Sumatra       186.30
9     EST001 2019-10-01  Sumatra       233.60
10    EST001 2019-11-01  Sumatra       230.40
11    EST001 2019-12-01  Sumatra       248.00
12    EST001 2020-01-01  Sumatra       259.00
13    EST001 2020-02-01  Sumatra       194.20
14    EST001 2020-03-01  Sumatra       187.90

## Generate Rainy Days

In [ ]:
# Jumlah rainy days harus berhubungan dengan rainfall.
rainy_day_noise = np.random.normal(
    loc=0,
    scale=1.5,
    size=len(df_base)
)

df_base["rainy_days"] = (
    df_base["rainfall_mm"] / 15
    + rainy_day_noise
).round()

df_base["rainy_days"] = (
    df_base["rainy_days"]
    .clip(lower=5, upper=28)
    .astype(int)
)

# Generate Fertilizer

In [ ]:
# Kita buat fertilizer berdasarkan luas area, sekitar 8–12 kg fertilizer / ha / month
fertilizer_rate = np.random.uniform(
    8,
    12,
    size=len(df_base)
)

fertilizer_noise = np.random.normal(
    0,
    0.05,
    size=len(df_base)
)

df_base["fertilizer_kg"] = (
    df_base["area_ha"]
    * fertilizer_rate
    * (1 + fertilizer_noise)
)

df_base["fertilizer_kg"] = (
    df_base["fertilizer_kg"]
    .clip(lower=0)
    .round(0)
)

## Generate Operational Working Days

In [ ]:
# Dalam satu bulan, effective working days kira-kira 22–27 hari.
df_base["working_days"] = np.random.randint(
    22,
    27,
    size=len(df_base)
)

## Generate Operational Disruptions

In [ ]:
# buat sebagian besar bulan memiliki disruption rendah.
df_base["disruption_days"] = np.random.poisson(
    lam=1.2,
    size=len(df_base)
)

df_base["disruption_days"] = (
    df_base["disruption_days"]
    .clip(lower=0, upper=7)
)

## buat Efek Umur Tanaman

In [ ]:
# Kita buat pola sederhana: tanaman muda → produksi meningkat, usia produktif → produksi optimal, usia tua → produktivitas mulai

def age_factor(age):
    if age < 6:
        return 0.75
    elif age < 10:
        return 0.90
    elif age <= 18:
        return 1.05
    elif age <= 22:
        return 0.95
    else:
        return 0.82

df_base["age_factor"] = df_base["plant_age_years"].apply(
    age_factor
)

## buat Efek Rainfall terhadap Produksi

In [ ]:
# Kita tidak ingin: semakin tinggi rainfall → produksi selalu semakin tinggi. Karena terlalu banyak hujan juga bisa mengganggu operasional. Kita buat rainfall optimal sekitar 180–280 mm.
def rainfall_factor(rainfall):
    if rainfall < 120:
        return 0.82
    elif rainfall < 180:
        return 0.92
    elif rainfall <= 280:
        return 1.05
    elif rainfall <= 350:
        return 0.98
    else:
        return 0.88

df_base["rainfall_production_factor"] = (
    df_base["rainfall_mm"].apply(rainfall_factor)
)

## Efek Fertilizer

In [ ]:
df_base["fertilizer_rate_kg_ha"] = (
    df_base["fertilizer_kg"]
    / df_base["area_ha"]
)

In [ ]:
def fertilizer_factor(rate):
    if rate < 8:
        return 0.90
    elif rate <= 11:
        return 1.00
    elif rate <= 13:
        return 1.04
    else:
        return 1.02

df_base["fertilizer_production_factor"] = (
    df_base["fertilizer_rate_kg_ha"]
    .apply(fertilizer_factor)
)

## Efek Operational Disruption

In [ ]:
# Semakin banyak disruption days, semakin rendah produksi.

df_base["operation_factor"] = (
    1 - (df_base["disruption_days"] * 0.025)
)

df_base["operation_factor"] = (
    df_base["operation_factor"]
    .clip(lower=0.80)
)

## Generate TBS Production

In [ ]:
# baseline: Area × Base Yield
random_noise = np.random.normal(
    loc=1.0,
    scale=0.05,
    size=len(df_base)
)

df_base["tbs_production_ton"] = (
    df_base["area_ha"]
    * df_base["base_yield_ton_ha"]
    * df_base["age_factor"]
    * df_base["rainfall_production_factor"]
    * df_base["fertilizer_production_factor"]
    * df_base["operation_factor"]
    * df_base["seasonal_factor"]
    * random_noise
)

In [ ]:
df_base["tbs_production_ton"] = (
    df_base["tbs_production_ton"]
    .clip(lower=0)
    .round(1)
)

In [ ]:
df_base[
    [
        "estate_id",
        "date",
        "area_ha",
        "plant_age_years",
        "rainfall_mm",
        "fertilizer_kg",
        "disruption_days",
        "tbs_production_ton"
    ]
].head(15)

,estate_id,date,area_ha,plant_age_years,rainfall_mm,fertilizer_kg,disruption_days,tbs_production_ton
0,EST001,2019-01-01,4250,9,265.40,"44,558.00",0,"8,132.40"
1,EST001,2019-02-01,4250,9,238.50,"51,306.00",1,"8,492.30"
2,EST001,2019-03-01,4250,9,247.20,"43,954.00",0,"8,186.50"
3,EST001,2019-04-01,4250,9,247.10,"36,406.00",3,"7,936.40"
4,EST001,2019-05-01,4250,9,192.10,"41,455.00",0,"8,551.40"
5,EST001,2019-06-01,4250,9,181.10,"40,334.00",0,"8,701.20"
6,EST001,2019-07-01,4250,9,215.50,"43,317.00",2,"9,134.30"
7,EST001,2019-08-01,4250,9,199.60,"32,804.00",0,"7,770.70"
8,EST001,2019-09-01,4250,9,186.30,"34,159.00",1,"8,254.10"
9,EST001,2019-10-01,4250,9,233.60,"51,248.00",1,"7,933.20"
10,EST001,2019-11-01,4250,9,230.40,"36,671.00",1,"7,918.20"
11,EST001,2019-12-01,4250,9,248.00,"51,928.00",0,"8,680.50"
12,EST001,2020-01-01,4250,10,259.00,"37,710.00",1,"8,318.10"
13,EST001,2020-02-01,4250,10,194.20,"41,093.00",0,"8,454.10"
14,EST001,2020-03-01,4250,10,187.90,"43,244.00",0,"9,736.50"

## Generate CPO Production

In [ ]:
# buat CPO berdasarkan TBS, gunakan extraction rate sekitar 18–22%.
cpo_extraction_rate = np.random.normal(
    loc=0.20,
    scale=0.015,
    size=len(df_base)
)

cpo_extraction_rate = np.clip(
    cpo_extraction_rate,
    0.17,
    0.23
)

df_base["cpo_extraction_rate"] = cpo_extraction_rate

df_base["cpo_production_ton"] = (
    df_base["tbs_production_ton"]
    * df_base["cpo_extraction_rate"]
).round(1)

## Generate Kernel Production

In [ ]:
# gunakan extraction rate sekitar 4–6%.
kernel_extraction_rate = np.random.normal(
    loc=0.05,
    scale=0.005,
    size=len(df_base)
)

kernel_extraction_rate = np.clip(
    kernel_extraction_rate,
    0.04,
    0.06
)

df_base["kernel_extraction_rate"] = (
    kernel_extraction_rate
)

df_base["kernel_production_ton"] = (
    df_base["tbs_production_ton"]
    * df_base["kernel_extraction_rate"]
).round(1)

## Buat Dataset Weather

In [ ]:
weather_columns = [
    "date",
    "estate_id",
    "rainfall_mm",
    "rainy_days"
]

df_weather = df_base[weather_columns].copy()

df_weather.head()

        date estate_id  rainfall_mm  rainy_days
0 2019-01-01    EST001       265.40          18
1 2019-02-01    EST001       238.50          17
2 2019-03-01    EST001       247.20          15
3 2019-04-01    EST001       247.10          17
4 2019-05-01    EST001       192.10          13

## Buat Dataset Operational

In [ ]:
operation_columns = [
    "date",
    "estate_id",
    "fertilizer_kg",
    "working_days",
    "disruption_days"
]

df_operation = df_base[operation_columns].copy()

df_operation.head()

        date estate_id  fertilizer_kg  working_days  disruption_days
0 2019-01-01    EST001      44,558.00            25                0
1 2019-02-01    EST001      51,306.00            23                1
2 2019-03-01    EST001      43,954.00            23                0
3 2019-04-01    EST001      36,406.00            23                3
4 2019-05-01    EST001      41,455.00            25                0

## Buat Dataset Production

In [ ]:
production_columns = [
    "date",
    "estate_id",
    "tbs_production_ton",
    "cpo_production_ton",
    "kernel_production_ton"
]

df_production = df_base[production_columns].copy()

df_production.head()

,date,estate_id,tbs_production_ton,cpo_production_ton,kernel_production_ton
0,2019-01-01,EST001,"8,132.40","1,600.40",487.90
1,2019-02-01,EST001,"8,492.30","1,805.10",443.20
2,2019-03-01,EST001,"8,186.50","1,597.90",413.10
3,2019-04-01,EST001,"7,936.40","1,398.50",415.70
4,2019-05-01,EST001,"8,551.40","1,856.50",513.10

## Dataset Estate

In [ ]:
estate_columns = [
    "estate_id",
    "estate_name",
    "region",
    "area_ha",
    "planting_year"
]

df_estate_final = df_estate[estate_columns].copy()

df_estate_final

  estate_id         estate_name      region  area_ha  planting_year
0    EST001   Estate Lampung 01     Sumatra     4250           2010
1    EST002   Estate Lampung 02     Sumatra     3800           2012
2    EST003    Estate Sumsel 01     Sumatra     5100           2009
3    EST004     Estate Jambi 01     Sumatra     4600           2011
4    EST005      Estate Riau 01     Sumatra     5500           2008
5    EST006    Estate Kalbar 01  Kalimantan     4100           2013
6    EST007   Estate Kalteng 01  Kalimantan     4700           2010
7    EST008    Estate Kaltim 01  Kalimantan     3900           2014
8    EST009  Estate Sulawesi 01    Sulawesi     3600           2011
9    EST010  Estate Sulawesi 02    Sulawesi     4300           2012

## Cek Relationship

In [ ]:
# Check duplicate estate-month
print(
    "Weather duplicates:",
    df_weather.duplicated(
        subset=["estate_id", "date"]
    ).sum()
)

print(
    "Operation duplicates:",
    df_operation.duplicated(
        subset=["estate_id", "date"]
    ).sum()
)

print(
    "Production duplicates:",
    df_production.duplicated(
        subset=["estate_id", "date"]
    ).sum()
)

Weather duplicates: 0
Operation duplicates: 0
Production duplicates: 0

## Cek Missing Values Sebelum Injection

In [ ]:
print("Weather missing:")
print(df_weather.isna().sum())

print("\nOperation missing:")
print(df_operation.isna().sum())

print("\nProduction missing:")
print(df_production.isna().sum())

Weather missing:
date           0
estate_id      0
rainfall_mm    0
rainy_days     0
dtype: int64

Operation missing:
date               0
estate_id          0
fertilizer_kg      0
working_days       0
disruption_days    0
dtype: int64

Production missing:
date                     0
estate_id                0
tbs_production_ton       0
cpo_production_ton       0
kernel_production_ton    0
dtype: int64

## Cek Produksi

In [ ]:
df_production.describe()

,date,tbs_production_ton,cpo_production_ton,kernel_production_ton
count,840,840.00,840.00,840.00
mean,2022-06-16 14:17:08.571428608,"9,454.52","1,887.30",472.16
min,2019-01-01 00:00:00,"5,437.40","1,017.30",222.60
25%,2020-09-23 12:00:00,"8,051.77","1,584.40",398.58
50%,2022-06-16 00:00:00,"9,299.45","1,871.45",462.05
75%,2024-03-08 18:00:00,"10,727.00","2,159.43",540.02
max,2025-12-01 00:00:00,"15,688.20","3,308.40",878.40
std,NaN,"1,813.75",391.36,104.28

In [ ]:
print(
    "Negative TBS:",
    (df_production["tbs_production_ton"] < 0).sum()
)

print(
    "Negative CPO:",
    (df_production["cpo_production_ton"] < 0).sum()
)

print(
    "Negative Kernel:",
    (df_production["kernel_production_ton"] < 0).sum()
)

Negative TBS: 0
Negative CPO: 0
Negative Kernel: 0

# SAVE

In [ ]:
df_estate_final.to_csv(
    RAW_DIR / "estate_master_clean.csv",
    index=False
)

df_weather.to_csv(
    RAW_DIR / "weather_data_clean.csv",
    index=False
)

df_operation.to_csv(
    RAW_DIR / "operation_data_clean.csv",
    index=False
)

df_production.to_csv(
    RAW_DIR / "production_data_clean.csv",
    index=False
)

## Copy Dataset untuk Data Quality Simulation

In [ ]:
weather_raw = df_weather.copy()
operation_raw = df_operation.copy()
production_raw = df_production.copy()

## Inject Missing Values

In [ ]:
# weather
weather_missing_idx = np.random.choice(
    weather_raw.index,
    size=15,
    replace=False
)

weather_raw.loc[
    weather_missing_idx,
    "rainfall_mm"
] = np.nan

In [ ]:
# operation
operation_missing_idx = np.random.choice(
    operation_raw.index,
    size=10,
    replace=False
)

operation_raw.loc[
    operation_missing_idx,
    "fertilizer_kg"
] = np.nan

In [ ]:
# production
production_missing_idx = np.random.choice(
    production_raw.index,
    size=8,
    replace=False
)

production_raw.loc[
    production_missing_idx,
    "tbs_production_ton"
] = np.nan

## Inject Duplicate Records

In [ ]:
# weather duplicates
weather_duplicates = weather_raw.sample(
    5,
    random_state=42
)

weather_raw = pd.concat(
    [weather_raw, weather_duplicates],
    ignore_index=True
)

In [ ]:
# operation duplicates
operation_duplicates = operation_raw.sample(
    5,
    random_state=42
)

operation_raw = pd.concat(
    [operation_raw, operation_duplicates],
    ignore_index=True
)

In [ ]:
# production duplicates
production_duplicates = production_raw.sample(
    5,
    random_state=42
)

production_raw = pd.concat(
    [production_raw, production_duplicates],
    ignore_index=True
)

## Inject Invalid Rainfall

In [ ]:
invalid_rainfall_idx = np.random.choice(
    weather_raw.index,
    size=5,
    replace=False
)

weather_raw.loc[
    invalid_rainfall_idx,
    "rainfall_mm"
] = -50

## Inject Invalid Fertilizer

In [ ]:
invalid_fertilizer_idx = np.random.choice(
    operation_raw.index,
    size=5,
    replace=False
)

operation_raw.loc[
    invalid_fertilizer_idx,
    "fertilizer_kg"
] = -1000

## Inject Invalid Working Days

In [ ]:
invalid_working_idx = np.random.choice(
    operation_raw.index,
    size=5,
    replace=False
)

operation_raw.loc[
    invalid_working_idx,
    "working_days"
] = 45

## Inject Invalid Production

In [ ]:
invalid_production_idx = np.random.choice(
    production_raw.index,
    size=5,
    replace=False
)

production_raw.loc[
    invalid_production_idx,
    "tbs_production_ton"
] = -500

## Inject Outlier

In [ ]:
outlier_idx = np.random.choice(
    production_raw.index,
    size=5,
    replace=False
)

production_raw.loc[
    outlier_idx,
    "tbs_production_ton"
] *= 2.5

production_raw.loc[
    outlier_idx,
    "tbs_production_ton"
] = (
    production_raw.loc[
        outlier_idx,
        "tbs_production_ton"
    ].round(1)
)

## Simpan Raw Dataset Bermasalah

In [ ]:
df_estate_final.to_csv(
    RAW_DIR / "estate_master.csv",
    index=False
)

weather_raw.to_csv(
    RAW_DIR / "weather_data.csv",
    index=False
)

operation_raw.to_csv(
    RAW_DIR / "operation_data.csv",
    index=False
)

production_raw.to_csv(
    RAW_DIR / "production_data.csv",
    index=False
)

## Validasi Akhir Dataset Raw

In [ ]:
print("=== WEATHER ===")
print("Rows:", len(weather_raw))
print("Duplicates:", weather_raw.duplicated().sum())
print("Missing:")
print(weather_raw.isna().sum())

print("\n=== OPERATION ===")
print("Rows:", len(operation_raw))
print("Duplicates:", operation_raw.duplicated().sum())
print("Missing:")
print(operation_raw.isna().sum())

print("\n=== PRODUCTION ===")
print("Rows:", len(production_raw))
print("Duplicates:", production_raw.duplicated().sum())
print("Missing:")
print(production_raw.isna().sum())

=== WEATHER ===
Rows: 845
Duplicates: 5
Missing:
date            0
estate_id       0
rainfall_mm    15
rainy_days      0
dtype: int64

=== OPERATION ===
Rows: 845
Duplicates: 5
Missing:
date                0
estate_id           0
fertilizer_kg      10
working_days        0
disruption_days     0
dtype: int64

=== PRODUCTION ===
Rows: 845
Duplicates: 5
Missing:
date                     0
estate_id                0
tbs_production_ton       8
cpo_production_ton       0
kernel_production_ton    0
dtype: int64

## Cek Invalid Values

In [ ]:
print(
    "Negative rainfall:",
    (weather_raw["rainfall_mm"] < 0).sum()
)

print(
    "Negative fertilizer:",
    (operation_raw["fertilizer_kg"] < 0).sum()
)

print(
    "Invalid working days:",
    (operation_raw["working_days"] > 31).sum()
)

print(
    "Negative TBS:",
    (production_raw["tbs_production_ton"] < 0).sum()
)

Negative rainfall: 5
Negative fertilizer: 5
Invalid working days: 5
Negative TBS: 5

## Summary Dataset

In [ ]:
summary = pd.DataFrame({
    "dataset": [
        "Estate Master",
        "Weather",
        "Operation",
        "Production"
    ],

    "rows": [
        len(df_estate_final),
        len(weather_raw),
        len(operation_raw),
        len(production_raw)
    ],

    "columns": [
        df_estate_final.shape[1],
        weather_raw.shape[1],
        operation_raw.shape[1],
        production_raw.shape[1]
    ]
})

summary

         dataset  rows  columns
0  Estate Master    10        5
1        Weather   845        4
2      Operation   845        5
3     Production   845        5